# **Numpy**

In [ ]:
##importing numpy

import numpy as np

arr = np.array([1,2,3,4,5,6])
print(type(arr))

ar2 = np.array(range(2,8,2))
print(ar2)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])
print(np.dot(A, B))  # Matrix multiplication


[[ 4  6]
 [10 12]]


In [ ]:
#creating an array filled with ones array([[1., 1., 1.],......
np.ones((5,3))

#creating an array filled with required element '8' array(array([[8, 8],......
np.full((2,2),8)

#creating an array filled with zeroes [[0., 0.],.......
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
#using range / arange for creating array

np.arange(1,10,2)

np.array(range(1,10,2))

#create a 3*3 matrix using range

np.zeros((9)).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#creating identity matrices
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

identity_matrix =   np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# find the shape of an array
identity_matrix.shape

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])


arr1 = np.array([[1,2,3],[4,5,6]])


arr1.shape
arr.shape

# find the dimensions of an array
arr.ndim

arr3 = np.zeros((3,3,3))

arr3.ndim

# find the datatype of elements

arr.dtype

dtype('int64')

In [ ]:
# change the datatype of elements of array

arr.dtype

str_arr = arr.astype(str)

print(str_arr.dtype)

<U21


In [ ]:
# functions in array

arr = np.arange(0,100,10)

print(arr)
print(arr.sum())
print(np.sum(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

[ 0 10 20 30 40 50 60 70 80 90]
450
450
45.0
825.0
90
0
28.722813232690143


In [ ]:
# indexing and slicing

arr = np.arange(0,100,5).reshape((4,5))

print(arr)
print(arr[0:3,2:4])


arr1 = np.arange(0,10)
print(arr1)
print(arr1[:])

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
[[10 15]
 [35 40]
 [60 65]]


In [ ]:
#splitting an array

arrx =  np.arange(0,20,2)

print(arrx)
print(np.split(arrx,2))

[ 0  2  4  6  8 10 12 14 16 18]
[array([0, 2, 4, 6, 8]), array([10, 12, 14, 16, 18])]


In [ ]:
prices =  np.arange(100,1000,100)
prices2 = [int (x) for x in prices]
discount = 10

final_prices = []

for x in prices2:
  i = x - (x*discount)/100
  final_prices.append(i)

print(final_prices)


#broadcasting

new_price = prices - (prices*10)/100
print(new_price)

arr2 = arr + 10


arr3 = np.array([1,2,3,4,5])
print(arr)
print(arr + arr3)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]
[[  1   7  13  19  25]
 [ 26  32  38  44  50]
 [ 51  57  63  69  75]
 [ 76  82  88  94 100]]


In [ ]:
#vectorization

list1 = [1,2,3]
list2 = [4,5,6]

final = []
for x,y in zip(list1,list2):
  i = x+y
  final.append(i)

print(final)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1+arr2



array([5, 7, 9])

In [ ]:
import numpy as np

a = np.array([[1], [2], [3]])   # shape (3,1)
b = np.array([10, 20, 30])      # shape (3,)

result = a + b  # shape becomes (3,3) due to broadcasting
print(result)


# Normalize each row of a 2D array using broadcasting and vectorization
data = np.array([[1, 2, 3], [4, 5, 6]])
mean = data.mean(axis=1, keepdims=True)  # shape (2,1)
normalized = data - mean
print(normalized)

[[-1.  0.  1.]
 [-1.  0.  1.]]


In [ ]:
## Handling missing values

arr = np.arange(0,24,2).reshape(3,4)
arr2 = np.array([1,np.nan,1])

narr = arr*arr2

print(arr2)


import numpy as np

arr = np.arange(0, 24, 2).reshape(4, 3)
arr2 = np.array([1, np.nan, 1])
narr = arr * arr2

print(np.isnan(narr))

cleaned = np.nan_to_num(narr, 100)

print(cleaned[1,1])

cleaned[1,1] = 2

cleaned

array([[ 0.,  0.,  4.],
       [ 6.,  2., 10.],
       [12.,  0., 16.],
       [18.,  0., 22.]])

# **Pandas**

In [2]:
import pandas as pd

a = [1,2,3]
b = pd.Series(a)


mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)


myvar

In [3]:
## encoding = "latin1" / "utf8"

cleaned_dataset = pd.read_csv("/content/cleaned_dataset.csv")

In [ ]:
## creating on datafram and exporting it to csv

data = {

      'Name':['Akshat','Pallav', 'Chetna'],
      'Age':[26,34,33],
      'Location':['Noida','Pune','Pune']
}

df = pd.DataFrame(data)
print(df)

df.to_csv('Output.csv', index= False)

df.to_excel('Output.xlsx')

df.to_json('Output.json')

In [ ]:
# display first and last rows

cleaned_dataset.head(10)
cleaned_dataset.tail()

In [ ]:
# Understanding the dataset
# No. of columns?
# No. of rows?
# missing data?
# datatype of contents?

cleaned_dataset.info()


print(cleaned_dataset.describe())


In [ ]:
## fining column names and number of rows and columns

print(cleaned_dataset.columns)
print(cleaned_dataset.shape)

In [ ]:
cleaned_dataset[cleaned_dataset['Artist']=='Gorillaz']

subset = cleaned_dataset[['Track','Views']]

list1 = ['Artist','Track', "Views"]

newdf1 =[cleaned_dataset[list1]]

## selecting rows based on our conditions

new_df = cleaned_dataset[(cleaned_dataset['Views'] >  72011645) & (cleaned_dataset['official_video'] == 'FALSE')]

new_df

In [ ]:
## use & for and , | for or

new_df = cleaned_dataset[(cleaned_dataset['Views'] >  72011645) | (cleaned_dataset['official_video'] == 'FALSE')]

new_df

In [1]:
## column add, update, delete
import numpy as np

cleaned_dataset['Like/Comment'] = cleaned_dataset['Likes']/cleaned_dataset['Comments']

cleaned_dataset['Like/Comment'] = cleaned_dataset['Like/Comment'].replace([np.inf, -np.inf],np.nan)

cleaned_dataset

# using insert
cleaned_dataset.insert(0,'ID', range(1, len(cleaned_dataset)+1))

cleaned_dataset

#  update

cleaned_dataset.loc[0,'Artist'] = 'New Gorillaz'

cleaned_dataset

cleaned_dataset['Danceability'] = cleaned_dataset['Danceability']/2


# deleting a column

cleaned_dataset.drop(columns='Like/Comment')


cleaned_dataset

In [81]:
## cleaning the dataset further

# nan -> Not a number
# none -> for object data type

new_df = cleaned_dataset

# i tried to create a copy of original dataset to perform operations but
# inplace = True caused changes in the original so i should have used -
# new_df = cleaned_dataset.copy()

new_df['Artist'].replace('Gorillaz', np.nan, inplace = True)

new_df

new_df['Artist'].replace(np.nan,'Gorillaz', inplace = True)

new_df.isnull()

# .dropna()

new_df.dropna(axis = 0, inplace = True)

new_df.isnull()

# .fillna()

df_copy = cleaned_dataset.copy()

df_copy.fillna('Red Hot Chili Peppers', inplace=True)

df_copy


# Interpolation


df_copy.loc[::3,'Likes'] = np.nan

print('befor interpolation')
print(df_copy['Likes'].head(20))

print('after_interpolation')
df_copy['Likes'] = df_copy['Likes'].interpolate(method= 'linear')
print(df_copy['Likes'].head(20))

#Interpolation Types




In [144]:
# Sorting and Aggregation

data = {
    'Name':['Akshat', 'Pallav', 'Chetna', 'Harshit'],
    'Age':[26,34,33,25],
    'Salary':[50000, 150000, 60000,35000 ]
}

df = pd.DataFrame(data)

data['Name'].extend(['chinku','Akarshi', 'Luvi'])
data['Age'].extend([32,31,23])
data['Salary'].extend([75000,23000,31000])

df['Bonus'] = (df['Salary']*.9)

df['Bonus'] = df['Bonus'].astype(int)

df.info()

df.sort_values(by = 'Salary', ascending=False, inplace = True)

# aggregation
# Summary Statistics

avg_salary = df['Salary'].mean()
print(avg_salary)

#Grouping

grouped = cleaned_dataset.groupby('Artist')['Views'].sum()

print(grouped.sort_values(ascending = False).head(10))



In [178]:
# Merging and Joining

# pd.merge(df1, df2, on = 'Column Name', How = 'Type of join')

df_customers = pd.DataFrame({
    'Customer_ID' : [1,2,3,4,5],
    'Name' : ['A','B','C','D','E']
})

df_orders = pd.DataFrame({
    'Customer_ID' : [1,2,3,4,5,6,7,8,9,10],
    'Order_amount': list(range(1000,11000,1000))
})

merged_df1 = pd.merge(df_customers, df_orders, on = 'Customer_ID', how = 'left')

print('This is left joined\n\n',merged_df1)

merged_df2 = pd.merge(df_customers, df_orders, on = 'Customer_ID', how = 'right')

print('This is right joined\n\n', merged_df2)

merged_df3 = pd.merge(df_customers, df_orders, on = 'Customer_ID', how = 'outer')

print('This is outer joined\n\n', merged_df3)


merged_df4 = pd.merge(df_customers, df_orders, how = 'cross')

print('This is cross joined\n\n', merged_df4)


In [ ]:
# concatinating dataframes
# either vertically or horizontally

df_region1 = pd.DataFrame ({
    'Customer_id' : [1,2],
    'Name':['Akshat','Luv']
})

df_region2 = pd.DataFrame ({
    'Customer_id' : [3,4],
    'Name' : ['Pallav', 'Chinku']
})

#concate vertically

df_concatv = pd.concat([df_region1,df_region2], axis= 0)

df_concatv

#concate Horizontally

df_concath = pd.concat([df_region1,df_region2], axis= 1)

df_concath

df_address = pd.DataFrame({
    'Address':['Noida','Pune']
})

new_df = pd.concat([df_region1,df_address], axis=1)
new_df

# Capstone

In [218]:
# installing required librarires

import pandas as pd
import numpy as np

# loading dataset csv
df = pd.read_csv('/content/employee_dataset_for_capstone.csv')

# Opening and checking the dataset

df.head(5)

df.info()

df.describe()

df.shape

df.size

In [262]:
# check missing values in the dataset
# pd.isna() and pd.isnull() are aliases — they point to the same function.

df.isna().sum()
df.isnull().sum()

# Columns - Age, Experience(Years), Salay(INR), Performance ratings have missing values
# which we'll fill

# Age will be filled with mean age
# I made a mistake here as i wrote =
# df['Age'] = df['Age'].fillna(df['Age'].mean(), inplace = True)
# which made the whole age column none as whenever we use inplace = true it
# returns none so whenever use inplace = True don't assign it's value to the
# original, we can use it with inplace also as
# df['Age'] = df['Age'].fillna(df['Age'],mean())

df['Age'].fillna(df['Age'].mean(), inplace = True)


df['Salay(INR)'] = df['Salay(INR)'].fillna(df['Salay(INR)'].mean())

df['Experience(Years)'] = df['Experience(Years)'].fillna(df['Experience(Years)'].median())

df['Performance rating'].fillna(df['Performance rating'].mean(), inplace = True)

# Replacing any inf or -inf values
# df.replace([np.inf, -np.inf], np.nan, inplace = True)


#selecting numeric datatype columns
number_df = df.select_dtypes(include=[np.number])
df.replace([np.inf, -np.inf], np.nan, inplace=True)


Emp_id     Name   Age     Salay(INR)  Experience(Years)       City  \
0    EMP0001  Harshit  60.0   49375.000000               25.0  Hyderabad   
1    EMP0002      Raj  50.0  160734.000000               35.0  Hyderabad   
2    EMP0003      Raj  36.0   36964.000000                0.0  Hyderabad   
3    EMP0004  Harshit  29.0  133429.000000                7.0    Chennai   
4    EMP0005     Neha  42.0   87215.000000               34.0  Bangalore   
..       ...      ...   ...            ...                ...        ...   
195  EMP0196    Divya  30.0  107056.066667               21.0  Bangalore   
196  EMP0197  Harshit  27.0   86040.000000                3.0  Bangalore   
197  EMP0198      Raj  37.0   48016.000000               21.0  Bangalore   
198  EMP0199   Chetna  50.0   43960.000000                1.0    Kolkata   
199  EMP0200     Neha  24.0   53591.000000                9.0    Kolkata   

     Department  Performance rating  
0     Marketing            2.911458  
1            HR            5.000000  
2    Operations            3.000000  
3       Finance            5.000000  
4         Sales            3.000000  
..          ...                 ...  
195   Marketing            4.000000  
196       Sales            2.000000  
197  Operations            3.000000  
198   Marketing            2.000000  
199     Finance            2.000000  

[200 rows x 8 columns]

In [ ]:
| Technique       | Best When...                            | Sensitive to Outliers? |
| --------------- | --------------------------------------- | ---------------------- |
| `mean`          | Data is normal, no outliers             | ✅ Yes                  |
| `median`        | Data is skewed or has outliers          | ❌ No                   |
| `interpolation` | Data is ordered/sequential (e.g., time) | Depends on method      |


In [272]:
# checking for duplicates

duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [Emp_id, Name, Age, Salay(INR), Experience(Years), City, Department, Performance rating]
Index: []


In [289]:
df['Salay(INR)'].rename('Salary', inplace = True)


df.rename(columns = {'Salay(INR)': 'Salary'}, inplace = True)

df

Emp_id     Name   Age         Salary  Experience(Years)       City  \
0    EMP0001  Harshit  60.0   49375.000000               25.0  Hyderabad   
1    EMP0002      Raj  50.0  160734.000000               35.0  Hyderabad   
2    EMP0003      Raj  36.0   36964.000000                0.0  Hyderabad   
3    EMP0004  Harshit  29.0  133429.000000                7.0    Chennai   
4    EMP0005     Neha  42.0   87215.000000               34.0  Bangalore   
..       ...      ...   ...            ...                ...        ...   
195  EMP0196    Divya  30.0  107056.066667               21.0  Bangalore   
196  EMP0197  Harshit  27.0   86040.000000                3.0  Bangalore   
197  EMP0198      Raj  37.0   48016.000000               21.0  Bangalore   
198  EMP0199   Chetna  50.0   43960.000000                1.0    Kolkata   
199  EMP0200     Neha  24.0   53591.000000                9.0    Kolkata   

     Department  Performance rating  
0     Marketing            2.911458  
1            HR            5.000000  
2    Operations            3.000000  
3       Finance            5.000000  
4         Sales            3.000000  
..          ...                 ...  
195   Marketing            4.000000  
196       Sales            2.000000  
197  Operations            3.000000  
198   Marketing            2.000000  
199     Finance            2.000000  

[200 rows x 8 columns]

In [312]:
df['Salary'].sort_values()

# there is not discrepancy in salary but for practice lets replace all salaries
# below 25k with 35k

df['Salary'] = np.where(df['Salary'] < 25000, df['Salary'].mean(), df['Salary'])

# remove rows where salary is too high or low

salary_mean = df['Salary'].mean()
salary_std = df['Salary'].std()
lowerbound = salary_mean - (3*salary_std)
upperbound = salary_mean + (3*salary_std)

print(upperbound)

df = df[(df['Salary']>=lowerbound) & (df['Salary'] <=upperbound)]

df.to_csv('Cleaned_Employee_dataset')

# Fin